- hosts: all
  tasks:
  - package: "name=httpd state=present"
  - copy: "src=/home/vikash/ansible/webserver/index.html  dest=/var/www/html"
  - service: "name=httpd state=started enabled=yes"
  - firewalld: "immediate=true port=80/tcp state=enabled
